Generate AAS JSON-LD context from meta model
aas-core-works/aas-core-codegen pull request #408
Opened 2023-09-27 14:14 UTC by Murloc6

This PR leads to add JSON-LD context generation feature using the meta model from aas-core-meta.

It adds the command such as:
```
aas-core-codegen \                                                                                                                                        
      --model_path ../aas-core-meta/aas_core_meta/v3rc2.py \
      --snippets_dir /tmp/aas/snippets \
      --output_dir /tmp/aas/ontology \
      --target jsonld
```

ping @wiresio @ethieblin

2023-09-27 14:27 UTC, Murloc6 commented
I set this PR as draft since I have to fix Mypy errors first

2023-09-27 14:29 UTC, wiresio commented
With the JSON-LD Context, AAS JSON documents can be transformed into JSON-LD and thus into triples, or AAS JSON can be built from graphs resulting from a corresponding SPARQL construct query.

In combination of both, a JSON transformation can be performed, e.g. Thing Description <-> Asset Interface Description Submodel.

We are happy to share this code with the community and are looking forward to a discussion about its usage.

2023-09-27 15:44 UTC, mristin commented
@wiresio @Murloc6 thanks! 

@wiresio I've just sent you a linkedin invite -- let's have a quick phone call before I start reviewing this PR?

2023-09-29 08:04 UTC, mristin requested changes
@Murloc6 @wiresio thanks a lot! Please see the comment below.

2023-10-06 11:18 UTC, wiresio commented on aas_core_codegen/main.py
> +    JSONLD = "jsonld"
```
# NOTE
# JSON-LD (JSON Linked Data) Context Generation
#
# Developed by Fabien Amarger, Elodie Thieblin, and Christian Glomb in order to generate an AAS JSON-LD Context. With the help of the JSON-LD Context AAS JSON files can be represented as triples. That enables applications to make use of Semantic technologies, such as storing of AAS data in triplestores or - with the help of appropriate SPARQL queries - data transformation, e.g., from AAS Asset Interface Description Submodel to W3C Web of Things Thing Description.
```

2023-10-06 11:22 UTC, mristin commented on aas_core_codegen/main.py
> +    JSONLD = "jsonld"
@Murloc6 could you please put this in code and wrap at 88 character line limit?

2023-10-06 11:23 UTC, mristin commented on aas_core_codegen/main.py
> +    JSONLD = "jsonld"
@wiresio could you please put github usernames in the parentheses or emails so that the maintainers know who to contact?

2023-10-07 08:02 UTC, mristin requested changes
@Murloc6 @wiresio thanks a lot for the changes! I added quite a few minor comments. Most of them are due to my own mistake that I haven't written a contributing guideline yet. Please fix them here to avoid later changes, and I'll write the contributing guidelines immediately afterwards.

2023-10-07 08:02 UTC, mristin commented on aas_core_codegen/main.py
> +    # JSON-LD (JSON Linked Data) Context Generation
@Murloc6 (This is the comment I had in mind re comment above for the documentation. I'd move it into the docstring and remove it here. Sorry for the zigzag.)

2023-10-11 09:30 UTC, Murloc6 commented
Thank you for your review :)
I took care of all comments and I simplify some part of the code. But mainly I simplify the number of commits to have only 5 since it started to be a very long pile of unnecessary separated commits.

Hope this fits your needs.

2023-10-11 09:49 UTC, mristin commented
Thanks, @Murloc6 ! I'll try to review it this week, worst case next week.

2023-10-19 08:36 UTC, Murloc6 commented
@mristin Apparently there are some review that I have to fix, but I don't know which one. Can you tell what is missing ?
Thank you :)

2023-10-19 15:12 UTC, mristin commented
> @mristin Apparently there are some review that I have to fix, but I don't know which one. Can you tell what is missing ? Thank you :)

@Murloc6 please see https://github.com/aas-core-works/aas-core-codegen/pull/408/files. For example: https://github.com/aas-core-works/aas-core-codegen/pull/408/files#r1349481243

2023-10-25 14:45 UTC, Murloc6 commented on aas_core_codegen/jsonld/main.py
> +    class_context_defintion: JsonLdType = {}
it is already defined inside the function and not as an argument here

2023-10-25 14:48 UTC, Murloc6 commented
> > @mristin Apparently there are some review that I have to fix, but I don't know which one. Can you tell what is missing ? Thank you :)
> 
> @Murloc6 please see https://github.com/aas-core-works/aas-core-codegen/pull/408/files. For example: https://github.com/aas-core-works/aas-core-codegen/pull/408/files#r1349481243

Sorry I missed these. There are now fixed, :) let me know if everything is fine for you ?

2023-10-25 15:26 UTC, Murloc6 commented
GitHub Actions will be fixed with https://github.com/aas-core-works/aas-core-codegen/pull/411

2023-10-26 08:07 UTC, Murloc6 commented
> > GitHub Actions will be fixed with #411
> 
> @Murloc6 thanks! I merged in #411 -- can you please rebase and see if the CI passes now?

pipeline is fixed :)

2023-10-27 12:34 UTC, mristin approved these changes

2023-10-27 12:36 UTC, merged