Generator for ProtoBuf (proto3)
aas-core-works/aas-core-codegen pull request #476
Opened 2024-04-19 13:43 UTC by TomGneuss

As by issue #475, we requested a new generator for ProtoBuf. With this pull-request we present a possible solution for that.
In contrast to other generators, it only requires the `structure` module.
Since ProtoBuf is only a configuration language, it does not support functionalities like verification or object-oriented patterns like _Visitor_.
Thus, the code-base is minimal because also the expected output is reduced compared to the normal Core SDK.

2024-04-20 00:14 UTC, mristin commented
@TomGneuss thanks a lot! Before I dig deeper, would you mind creating a separate smaller pull request for the renaming pascal to snake case? I was at first quite confused why other generators were changed, and this might make exploration of the history more difficult down the line.

If you lack time, I can do it for you -- please let me know what is easier for you.

2024-04-22 10:46 UTC, TomGneuss commented
I ran the code-formatting script. As in #478, the mypy part fails.

I also discovered an issue in the generated proto files regarding properties that are not concrete types but interfaces. Since proto3 does not support interfaces (and inheritance in general), i fixed it by using the "oneof" keyword or introduced a *choice-message where necessary.

2024-04-22 15:10 UTC, g1zzm0 requested changes

2024-04-22 15:10 UTC, g1zzm0 commented on aas_core_codegen/cpp/description.py
> +
```suggestion
```

2024-04-22 15:10 UTC, g1zzm0 commented on aas_core_codegen/cpp/constants/_generate.py
> +
```suggestion
```

2024-04-22 15:10 UTC, g1zzm0 commented on aas_core_codegen/cpp/enhancing/__init__.py
> +
```suggestion
```

2024-04-22 15:10 UTC, g1zzm0 commented on aas_core_codegen/cpp/main.py
> +
```suggestion
```

2024-04-22 15:10 UTC, g1zzm0 commented on aas_core_codegen/cpp/optionaling.py
> +
```suggestion
```

2024-04-22 15:10 UTC, g1zzm0 commented on aas_core_codegen/cpp/stringification/__init__.py
> +
```suggestion
```

2024-04-22 15:10 UTC, g1zzm0 commented on aas_core_codegen/cpp/structure/_generate.py
> +
```suggestion
```

2024-04-23 04:04 UTC, g1zzm0 requested changes
Remove unnecessary blanks and empty lines

2024-04-23 04:04 UTC, g1zzm0 commented on aas_core_codegen/typescript/transpilation.py
> +
```suggestion
```

2024-04-23 04:04 UTC, g1zzm0 commented on aas_core_codegen/typescript/unrolling.py
> +
```suggestion
```

2024-04-23 04:04 UTC, g1zzm0 commented on aas_core_codegen/typescript/verification/_generate.py
> +
```suggestion
```

2024-04-23 04:04 UTC, g1zzm0 commented on aas_core_codegen/xsd/naming.py
> +
```suggestion
```

2024-04-23 04:04 UTC, g1zzm0 commented on aas_core_codegen/yielding/linear.py
> +
```suggestion
```

2024-04-23 04:04 UTC, g1zzm0 commented on setup.py
> +
```suggestion
```

2024-04-23 04:30 UTC, g1zzm0 approved these changes
lgtm

2024-04-23 05:51 UTC, mristin commented
@g1zzm0 why did you remove the empty lines? Wouldn't `black` take care of that?

2024-04-23 06:04 UTC, g1zzm0 commented
> @g1zzm0 why did you remove the empty lines? Wouldn't `black` take care of that?

idk. Didn't work for us. Fixed minor bugs in the proto gen.

2024-04-23 06:05 UTC, mristin commented
@TomGneuss please let me know when you sync the pull request with the main branch and when it is ready for review.

2024-04-23 06:08 UTC, mristin commented
@g1zzm0 @TomGneuss please make sure that you create separate pull requests for all the non-protobuf related changes. Otherwise, it is very hard to follow the git history and also to review.

2024-04-23 06:15 UTC, mristin commented
> > @g1zzm0 why did you remove the empty lines? Wouldn't `black` take care of that?
> 
> idk. Didn't work for us. Fixed minor bugs in the proto gen.

I see the changes now also in the web. Please revert them (the removal of blank lines). We intentionally put a blank line after the module docstring (and I think `black` does so to?) for readability. Let's leave the formatting as it is for now.

2024-04-23 06:20 UTC, mristin commented
You can try in your virtual environment:
```
pip3 uninstall black
pip3 install -e .[dev]
pip3 list 
black --version
```

Maybe you have a system-wide installed black which eclipses the local one?

2024-04-23 06:45 UTC, g1zzm0 commented
> You can try in your virtual environment:
We used the virtual Env like described in: https://github.com/aas-core-works/aas-core-codegen/blob/main/CONTRIBUTING.rst#create-a-development-environment

2024-04-23 06:48 UTC, mristin commented
> > You can try in your virtual environment:
> > We used the virtual Env like described in: https://github.com/aas-core-works/aas-core-codegen/blob/main/CONTRIBUTING.rst#create-a-development-environment

Have you also installed black in this step?
https://github.com/aas-core-works/aas-core-codegen/blob/main/CONTRIBUTING.rst#install-development-dependencies

What do you get in the activated virtual environment when you call:
```
black --version
```
?

2024-04-23 06:59 UTC, g1zzm0 commented
> Have you also installed black in this step? https://github.com/aas-core-works/aas-core-codegen/blob/main/CONTRIBUTING.rst#install-development-dependencies

Yes.

> What do you get in the activated virtual environment when you call:
> 
> ```
> black --version
> ```
> 
> ?
22.3.0

2024-04-23 07:11 UTC, merged

2024-04-23 07:32 UTC, mristin commented
@g1zzm0 @TomGneuss can you give me some hint what changed here?

aas_core_codegen/intermediate/_translate.py

Only formatting, right?